version: '3'

services:
  nginx:
    image: nginx:latest  # Sử dụng image Nginx mới nhất
    container_name: nginx-container
    ports:
      - "8080:80"  # Ánh xạ cổng 8080 của host với cổng 80 của container
    volumes:
      - ./html:/usr/share/nginx/html  # Gắn thư mục html để hiển thị nội dung web
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
